---

application           : "flice-core"
application-client-id : "Y29yZQ=="

datasource: 

  user            : root
  password        : 
  url             : jdbc:mysql://localhost:3306/flice-core
  driverClass     : com.mysql.jdbc.Driver

  validationQuery : SELECT 1
  minSize         : 1

  properties:
    hibernate.dialect       : org.hibernate.dialect.MySQLDialect
    hibernate.hbm2ddl.auto  : create-drop


logging:
  level: INFO