---

#Custom Applications Config
application           : "flice-security"
application-client-id : "Y29yZQ=="

coreApiUrl        : "http://core:8080/core/api/user/verify"

#Commom Applications Config

server:
  applicationConnectors:
  - type: http 
    port: 8081
  adminConnectors:
  - type: http
    port: 9091

datasource: 

  user            : root
  password        : ZmxpY2UNCg==
  url             : jdbc:mysql://mysql:3306/flice-security
  driverClass     : com.mysql.jdbc.Driver

  validationQuery : SELECT 1
  minSize         : 1

  properties:
    hibernate.dialect       : org.hibernate.dialect.MySQLDialect
    hibernate.hbm2ddl.auto  : create-drop

allowedGrantTypes:
  - password

httpClient:
  timeout                 : 20000ms
  connectionTimeout       : 20000ms
  timeToLive              : 1h
  cookiesEnabled          : false
  maxConnections          : 1024
  maxConnectionsPerRoute  : 1024
  keepAlive               : 0ms
  retries                 : 0
  userAgent               : flice-security  

logging:
  level: INFO