---

#Custom Applications Config
application           : "flice-core"
applicationClientId   : "Y29yZQ=="

securityApiUrl        : "http://localhost:8081/security/api/token/verify"

#Commom Applications Config
server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 9090

#Database Application Config

datasource:

  user            : root
  password        :
  url             : jdbc:mysql://localhost:3306/flice-core
  driverClass     : com.mysql.jdbc.Driver

  validationQuery : SELECT 1
  minSize         : 1

  properties:
    hibernate.dialect       : org.hibernate.dialect.MySQLDialect
    hibernate.hbm2ddl.auto  : none
    # hibernate.show_sql      : true
    # hibernate.format_sql    : true

flyway:
  encoding: UTF-8

logging:
  level: INFO

httpClient:
  timeout                 : 20000ms
  connectionTimeout       : 20000ms
  timeToLive              : 1h
  cookiesEnabled          : false
  maxConnections          : 1024
  maxConnectionsPerRoute  : 1024
  keepAlive               : 0ms
  retries                 : 0
  userAgent               : flice-core