---

#Custom Applications Config
application           : "flice-core"
applicationClientId : "Y29yZQ=="

securityApiUrl        : "http://security:8081/security/api/token/verify"

#Commom Applications Config

logging:
  level: INFO

server:
  applicationConnectors:
  - type: http 
    port: 8080
  adminConnectors:
  - type: http
    port: 9090

#Database Application Config

datasource: 

  user            : root
  password        : ZmxpY2UNCg==
  url             : jdbc:mysql://mysql:3306/flice-core
  driverClass     : com.mysql.jdbc.Driver

  validationQuery : SELECT 1
  minSize         : 1

  properties:
    hibernate.dialect       : org.hibernate.dialect.MySQLDialect
    hibernate.hbm2ddl.auto  : none
    jadira.usertype.autoRegisterUserTypes : true


httpClient:
  timeout                 : 20000ms
  connectionTimeout       : 20000ms
  timeToLive              : 1h
  cookiesEnabled          : false
  maxConnections          : 1024
  maxConnectionsPerRoute  : 1024
  keepAlive               : 0ms
  retries                 : 0
  userAgent               : flice-core